title: Taylor Freiner 
email: tfreiner@gmail.com
description: Computer Science Major at the University of Missouri - St. Louis
show_downloads: false 
is_project_page: true
url: "http://taylorfreiner.com"
linkedin_username: taylorfreiner
github_username:  tfreiner
google_analytics:
theme: jekyll-theme-cayman 
